config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'forecasts#new'
  get 'welcome/index'
  resources :codes
  resources :forecasts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/forecast.rb
class Forecast
  include ActiveModel::Model 
  include ActiveModel::Attributes

  attribute :battery_capacity, :decimal, default: 50.00
  attribute :battery_level_at_the_beginning, :integer, default: 20
  attribute :battery_level_at_the_end, :integer, default: 80
  attribute :power_output, :decimal, default: 3.65
  attribute :elapsed, :time, default: '8:00:00'
  attribute :power_output_calculated, :decimal
  attribute :elapsed_calculated, :time

  validates :battery_capacity, presence: true
  validates :battery_level_at_the_beginning, presence: true
  validates :battery_level_at_the_end, presence: true
  validates :power_output, presence: true
  validates :elapsed, presence: true

  def calculate_fields
      energy_required = ((battery_level_at_the_end * battery_capacity) / 100) - ((battery_level_at_the_beginning * battery_capacity) / 100) 
      elapsed_decimal = elapsed.to_time.hour + elapsed.to_time.min / 60.00
      self.power_output_calculated = energy_required / elapsed_decimal
      elapsed_decimal_calculated = (energy_required / power_output).round(2)
      hours_elapsed = elapsed_decimal_calculated.to_i
      minutes_elapsed = (elapsed_decimal_calculated - hours_elapsed ) * 60
      self.elapsed_calculated = [hours_elapsed, minutes_elapsed, 0].join(':')
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController

    require 'rqrcode'
    require 'uri'

    def new
        @logo = "with"
    end
    
    def create

        code = params[:code]

        @url = code[:url]

        if @url =~ URI::regexp

            qrcode = RQRCode::QRCode.new(@url)

            output_size = 512
        
            qrcode_png = qrcode.as_png(
                  resize_gte_to: false,
                  resize_exactly_to: false,
                  fill: 'white',
                  color: 'black',
                  size: output_size,
                  border_modules: 4,
                  module_px_size: 6,
                  file: nil # path to write
                  )

            puts params[:logo]

            if params[:logo] == "with"
        
                original_logo = ChunkyPNG::Image.from_file("./app/assets/images/logo2.png")
            
                logo = original_logo.resize(output_size / 4, output_size /4)
                
                height = (qrcode_png.dimension.height / 2).floor - (logo.dimension.height / 2).floor
                width  = (qrcode_png.dimension.width  / 2).floor - (logo.dimension.width  / 2).floor
                
                @qr = qrcode_png.compose(logo, width, height)
            
            else

                @qr = qrcode_png

            end

        else

            redirect_to request.referer, alert: "El texto introducido no es una url correcta."
        
        end
    
    end
end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController
      def show
      end
    
      def new
        @forecast = Forecast.new
      end
    
      def create
        @forecast = Forecast.new(recharge_params)
    
        if @forecast.calculate_fields
          render :show
        else
          render :new, status: :unprocessable_entity
        end
    
      end
     
      private
        def recharge_params
          params.require(:forecast).permit(:battery_capacity, :battery_level_at_the_beginning, :battery_level_at_the_end, :power_output, :elapsed)
        end
    
    end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/codes/create.html.erb
<figure class="figure" >
  <a href="<%= @qr.to_data_url %>" download="qrcode.png">
    <img src="<%= @qr.to_data_url %>" class="figure-img img-fluid rounded" alt="qrcode.png" />
  </a>
  <figcaption class="figure-caption text-right"><code><%= @url %></code></figcaption>
</figure>
<a href="<%= @url %>" class="btn btn-secondary">Ver enlace</a>

app/views/codes/new.html.erb
<div class="container">
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %>">
      <%= value %>
    </div>
  <% end %>

  <%= yield %>
</div>
<h1>Pon la dirección de la página web:</h1>
<h3>La url tiene que empezar por <code>http://</code> o <code>https://</code>. Si no, no va a funcionar...</h3>
<%= form_with scope: :code, url: codes_path, local: true do |form| %>
    <div class="form-group">
      <%= form.text_field(:url, class: "form-control", placeholder: "https://www.ejemplo.com/mas-ejemplos") %>
      </div>   
      <div class="form-group">
        <div class="form-check form-check-inline">
        <%= radio_button_tag(:logo, "with", true, class: "form-check-input") %>
        <%= label_tag(:logo, "Con logo", class: "form-check-label") %>
      </div>
      <div class="form-check form-check-inline">
        <%= radio_button_tag(:logo, "without", false, class: "form-check-input") %>
        <%= label_tag(:logo, "Sin logo", class: "form-check-label") %>
      </div>
    </div>   
    <div class="form-group">
      <%= form.submit("Crear código QR", class: "btn btn-secondary") %>
    </div>
<% end %>

app/views/forecasts/_form.html.erb
<%= form_with model: forecast do |form| %>
    <div class="col-md-12 justify-content-center">

    <div class="row mb-3">
        <%= form.label "Capacidad de la batería", class: 'col-sm-6 col-form-label' %>
        <div class="col-sm-6">
            <%= form.number_field :battery_capacity, step: 0.01, class: 'form-control' %>
        </div>
        <% @forecast.errors.full_messages_for(:battery_capacity).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div class="row mb-3">
        <%= form.label "Nivel de batería inicial", class: 'col-sm-6 col-form-label' %>
        <div class="col-sm-6">
            <%= form.number_field :battery_level_at_the_beginning, step: 1, class: 'form-control' %>
        </div>
        <% @forecast.errors.full_messages_for(:battery_level_at_the_beginning).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    
    <div class="row mb-3">
        <%= form.label "Nivel de batería final", class: 'col-sm-6 col-form-label' %>
        <div class="col-sm-6">
            <%= form.number_field :battery_level_at_the_end, step: 1, class: 'form-control' %>
        </div>
        <% @forecast.errors.full_messages_for(:battery_level_at_the_end).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    
    <div class="row mb-3">
        <%= form.label "Potencia media del punto de recarga", class: 'col-sm-6 col-form-label' %>
        <div class="col-sm-6">
            <%= form.number_field :power_output, step: 0.01, class: 'form-control' %>
        </div>
        <% @forecast.errors.full_messages_for(:power_output).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    
    <div class="row mb-3">
        <%= form.label "Duración de la recarga", class: 'col-sm-6 col-form-label' %>
        <div class="col-sm-6">
            <%= form.time_field :elapsed, class: 'form-control' %>
        </div>
        <% @forecast.errors.full_messages_for(:elapsed).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    
    <div>
        <%= form.submit class: 'btn btn-primary' %>
    </div>

    </div>
<% end %>

app/views/forecasts/new.html.erb
<h2>Nuevo cálculo</h2>

<%= render "form", forecast: @forecast %>

app/views/forecasts/show.html.erb
<div class="col-md-12 justify-content-center">

    <h4>Previsión de recarga</h4>

    <dl class="row">

        <dt class="col-sm-4">Capacidad de la batería</dt>
        <dd class="col-sm-8"><%= @forecast.battery_capacity %></dd>
  
        <dt class="col-sm-4">Nivel de batería inicial</dt>
        <dd class="col-sm-8"><%= @forecast.battery_level_at_the_beginning %>%</dd>

        <dt class="col-sm-4">Nivel de batería final</dt>
        <dd class="col-sm-8"><%= @forecast.battery_level_at_the_end %>%</dd>

        <dt class="col-sm-4">Potencia media del punto de recarga</dt>
        <dd class="col-sm-8">
            <p><%= @forecast.power_output %> kW</p>
            <p>Alcanzará el nivel de batería deseado en <%= @forecast.elapsed_calculated.strftime("%H:%M") %></p>
        </dd>
  
        <dt class="col-sm-4">Duración de la recarga</dt>
        <dd class="col-sm-8">
            <p><%= @forecast.elapsed.strftime("%H:%M") %></p>
            <p>Alcanzará el nivel de batería deseado con una potencia de <%= @forecast.power_output_calculated %> kW</p>
        </dd>
    
    </dl>

</div>

<%= link_to "Nueva estimación", new_forecast_path, class: 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Utilidades</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application" %>
  </head>

  <body class="bg-light text-center">
    <main role="main" class="container">
      <div class="p-5 rounded">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/welcome/index.html.erb
<h1 class="cover-heading">Bienvenido a la web de Utilidades</h1>
<p class="lead">
    <%= link_to 'Generar un código QR', {controller: 'codes', action: 'new'}, class: 'btn btn-lg btn-secondary' %>
</p>